from typing import List

from src.cmu_graphics.libs.pygame_loader.modules.pygame_win_64_312.pygame.event import Event

def init() -> None: ...
def get_init() -> bool: ...
def pump() -> None: ...
def wait() -> Event: ...
def poll() -> Event: ...
def get() -> List[Event]: ...
def post(event: Event) -> None: ...
